"use client";

import React from "react";
import DynamicNodes, { DynamicNodeItem, DynamicNodeLink } from "@/app/the-actual-components/dynamic-nodes/DynamicNodes";

export default function DynamicNodesDemo() {
  const nodes: DynamicNodeItem[] = [
    {
      dynamicNodeId: "lang-pr",
      dynamicNodeText: "Language",
      dynamicNodeInitialX: 18,
      dynamicNodeInitialXUnit: "%",
      dynamicNodeInitialY: 68,
      dynamicNodeInitialYUnit: "%",
      dynamicNodeRadius: 16,
      dynamicNodeFillColor: "#777",
      dynamicNodeGlowColor: "#6a6a6a",
      dynamicNodeGlowBlur: 20,
      dynamicNodeTextColor: "#FFFFFF",
      dynamicNodeFontFamily: "Inter",
      dynamicNodeFontSize: 20,
      dynamicNodeFontWeight: 900,
      dynamicNodeTextDirection: "ltr",
      dynamicNodeLabelSide: "right",
      dynamicNodeLabelGap: 14,
      dynamicNodeVelocityX: 0.36,
      dynamicNodeVelocityY: -0.2,
      dynamicNodeAutoTextScale: true,
      dynamicNodeAutoTextFontSize: 16,
    },
    {
      dynamicNodeId: "lang-en",
      dynamicNodeText: "English",
      dynamicNodeInitialX: 28,
      dynamicNodeInitialXUnit: "%",
      dynamicNodeInitialY: 44,
      dynamicNodeInitialYUnit: "%",
      dynamicNodeRadius: 9,
      dynamicNodeFillColor: "#FFFFFF",
      dynamicNodeGlowColor: "#FFFFFF",
      dynamicNodeGlowBlur: 12,
      dynamicNodeTextColor: "#FFFFFF",
      dynamicNodeFontSize: 14,
      dynamicNodeFontWeight: 700,
      dynamicNodeTextDirection: "ltr",
      dynamicNodeLabelSide: "right",
      dynamicNodeLabelGap: 10,
      dynamicNodeVelocityX: -0.3,
      dynamicNodeVelocityY: 0.18,
      dynamicNodeAutoTextScale: true,
      dynamicNodeAutoTextFontSize: 14,
    },
    {
      dynamicNodeId: "lang-he",
      dynamicNodeText: "עברית",
      dynamicNodeInitialX: 26,
      dynamicNodeInitialXUnit: "%",
      dynamicNodeInitialY: 78,
      dynamicNodeInitialYUnit: "%",
      dynamicNodeRadius: 9,
      dynamicNodeFillColor: "#9625FF",
      dynamicNodeGlowColor: "#9625FF",
      dynamicNodeGlowBlur: 10,
      dynamicNodeTextColor: "#FFFFFF",
      dynamicNodeFontSize: 14,
      dynamicNodeFontWeight: 500,
      dynamicNodeTextDirection: "rtl",
      dynamicNodeLabelSide: "left",
      dynamicNodeLabelGap: 10,
      dynamicNodeVelocityX: 0.28,
      dynamicNodeVelocityY: -0.22,
      dynamicNodeAutoTextScale: true,
      dynamicNodeAutoTextFontSize: 14,
    },
    {
      dynamicNodeId: "lang-jp",
      dynamicNodeText: "日本語",
      dynamicNodeInitialX: 38,
      dynamicNodeInitialXUnit: "%",
      dynamicNodeInitialY: 60,
      dynamicNodeInitialYUnit: "%",
      dynamicNodeRadius: 9,
      dynamicNodeBorderRadius: 5,
      dynamicNodeFillColor: "#3CA29E",
      dynamicNodeGlowColor: "#3CA29E",
      dynamicNodeGlowBlur: 10,
      dynamicNodeTextColor: "#25FFE7",
      dynamicNodeFontFamily: "Inter",
      dynamicNodeFontSize: 14,
      dynamicNodeFontWeight: 700,
      dynamicNodeTextDirection: "ltr",
      dynamicNodeLabelSide: "right",
      dynamicNodeLabelGap: 10,
      dynamicNodeVelocityX: -0.18,
      dynamicNodeVelocityY: 0.15,
      dynamicNodeAutoTextScale: true,
      dynamicNodeAutoTextFontSize: 14,
    },
    {
      dynamicNodeId: "lang-it",
      dynamicNodeText: "Italiano",
      dynamicNodeInitialX: 31,
      dynamicNodeInitialXUnit: "%",
      dynamicNodeInitialY: 85,
      dynamicNodeInitialYUnit: "%",
      dynamicNodeRadius: 9,
      dynamicNodeFillColor: "#FF25C5",
      dynamicNodeGlowColor: "#FF25C5",
      dynamicNodeGlowBlur: 10,
      dynamicNodeTextColor: "#FFFFFF",
      dynamicNodeFontSize: 14,
      dynamicNodeFontWeight: 700,
      dynamicNodeTextDirection: "ltr",
      dynamicNodeLabelSide: "right",
      dynamicNodeLabelGap: 10,
      dynamicNodeVelocityX: 0.2,
      dynamicNodeVelocityY: -0.14,
      dynamicNodeAutoTextScale: true,
      dynamicNodeAutoTextFontSize: 14,
    },

    {
      dynamicNodeId: "fruit-pr",
      dynamicNodeText: "פרי",
      dynamicNodeInitialX: 62,
      dynamicNodeInitialXUnit: "%",
      dynamicNodeInitialY: 68,
      dynamicNodeInitialYUnit: "%",
      dynamicNodeRadius: 16,
      dynamicNodeFillColor: "#2558FF",
      dynamicNodeGlowColor: "#2558FF",
      dynamicNodeGlowBlur: 22,
      dynamicNodeTextColor: "#FFFFFF",
      dynamicNodeFontFamily: "Inter",
      dynamicNodeFontSize: 20,
      dynamicNodeFontWeight: 900,
      dynamicNodeTextDirection: "rtl",
      dynamicNodeLabelSide: "left",
      dynamicNodeLabelGap: 14,
      dynamicNodeVelocityX: -0.38,
      dynamicNodeVelocityY: 0.24,
      dynamicNodeAutoTextScale: true,
      dynamicNodeAutoTextFontSize: 20,
    },
    {
      dynamicNodeId: "fruit-apple",
      dynamicNodeText: "תפוח",
      dynamicNodeInitialX: 54,
      dynamicNodeInitialXUnit: "%",
      dynamicNodeInitialY: 47,
      dynamicNodeInitialYUnit: "%",
      dynamicNodeRadius: 10,
      dynamicNodeFillColor: "#25FF5F",
      dynamicNodeGlowColor: "#25FF5F",
      dynamicNodeGlowBlur: 12,
      dynamicNodeTextColor: "#FFFFFF",
      dynamicNodeFontSize: 14,
      dynamicNodeFontWeight: 700,
      dynamicNodeTextDirection: "rtl",
      dynamicNodeLabelSide: "left",
      dynamicNodeLabelGap: 10,
      dynamicNodeVelocityX: 0.24,
      dynamicNodeVelocityY: 0.16,
      dynamicNodeAutoTextScale: true,
      dynamicNodeAutoTextFontSize: 14,
    },
    {
      dynamicNodeId: "fruit-plum",
      dynamicNodeText: "שזיף",
      dynamicNodeInitialX: 50,
      dynamicNodeInitialXUnit: "%",
      dynamicNodeInitialY: 80,
      dynamicNodeInitialYUnit: "%",
      dynamicNodeRadius: 10,
      dynamicNodeFillColor: "#7A25FF",
      dynamicNodeGlowColor: "#7A25FF",
      dynamicNodeGlowBlur: 12,
      dynamicNodeTextColor: "#FFFFFF",
      dynamicNodeFontSize: 14,
      dynamicNodeFontWeight: 700,
      dynamicNodeTextDirection: "rtl",
      dynamicNodeLabelSide: "right",
      dynamicNodeLabelGap: 10,
      dynamicNodeVelocityX: -0.2,
      dynamicNodeVelocityY: -0.22,
      dynamicNodeAutoTextScale: true,
      dynamicNodeAutoTextFontSize: 14,
    },
    {
      dynamicNodeId: "fruit-orange",
      dynamicNodeText: "תפוז",
      dynamicNodeInitialX: 76,
      dynamicNodeInitialXUnit: "%",
      dynamicNodeInitialY: 58,
      dynamicNodeInitialYUnit: "%",
      dynamicNodeRadius: 10,
      dynamicNodeFillColor: "#FF2534",
      dynamicNodeGlowColor: "#FF2534",
      dynamicNodeGlowBlur: 12,
      dynamicNodeTextColor: "#FFFFFF",
      dynamicNodeFontSize: 14,
      dynamicNodeFontWeight: 700,
      dynamicNodeTextDirection: "rtl",
      dynamicNodeLabelSide: "left",
      dynamicNodeLabelGap: 10,
      dynamicNodeVelocityX: 0.16,
      dynamicNodeVelocityY: 0.1,
      dynamicNodeAutoTextScale: true,
      dynamicNodeAutoTextFontSize: 14,
    },
    {
      dynamicNodeId: "fruit-peach",
      dynamicNodeText: "Peach",
      dynamicNodeInitialX: 74,
      dynamicNodeInitialXUnit: "%",
      dynamicNodeInitialY: 84,
      dynamicNodeInitialYUnit: "%",
      dynamicNodeRadius: 10,
      dynamicNodeFillColor: "#FF5F25",
      dynamicNodeGlowColor: "#FF5F25",
      dynamicNodeGlowBlur: 12,
      dynamicNodeTextColor: "#FFFFFF",
      dynamicNodeFontSize: 14,
      dynamicNodeFontWeight: 700,
      dynamicNodeTextDirection: "ltr",
      dynamicNodeLabelSide: "right",
      dynamicNodeLabelGap: 10,
      dynamicNodeVelocityX: -0.18,
      dynamicNodeVelocityY: -0.15,
      dynamicNodeAutoTextScale: true,
      dynamicNodeAutoTextFontSize: 14,
    },
  ];

  const links: DynamicNodeLink[] = [
    {
      dynamicLinkFromIds: ["lang-pr"],
      dynamicLinkToIds: ["lang-en"],
      dynamicLinkColor: "#363636",
      dynamicLinkWidth: 1.5,
      dynamicLinkDash: [6, 5],
    },
    {
      dynamicLinkFromIds: ["lang-pr"],
      dynamicLinkToIds: ["lang-he"],
      dynamicLinkColor: "#363636",
      dynamicLinkWidth: 1.5,
      dynamicLinkDash: [6, 5],
    },
    {
      dynamicLinkFromIds: ["lang-pr"],
      dynamicLinkToIds: ["lang-jp"],
      dynamicLinkColor: "#363636",
      dynamicLinkWidth: 1.5,
      dynamicLinkDash: [6, 5],
    },
    {
      dynamicLinkFromIds: ["lang-pr"],
      dynamicLinkToIds: ["lang-it"],
      dynamicLinkColor: "#363636",
      dynamicLinkWidth: 1.5,
      dynamicLinkDash: [6, 5],
    },

    {
      dynamicLinkFromIds: ["fruit-pr"],
      dynamicLinkToIds: ["fruit-apple"],
      dynamicLinkColor: "rgba(168,85,247,0.55)",
      dynamicLinkWidth: 1.5,
      dynamicLinkDash: [5, 5],
    },
    {
      dynamicLinkFromIds: ["fruit-pr"],
      dynamicLinkToIds: ["fruit-orange"],
      dynamicLinkColor: "rgba(168,85,247,0.55)",
      dynamicLinkWidth: 1.5,
      dynamicLinkDash: [5, 5],
    },
    {
      dynamicLinkFromIds: ["fruit-pr"],
      dynamicLinkToIds: ["fruit-peach"],
      dynamicLinkColor: "rgba(168,85,247,0.55)",
      dynamicLinkWidth: 1.5,
      dynamicLinkDash: [5, 5],
    },
    {
      dynamicLinkFromIds: ["fruit-pr"],
      dynamicLinkToIds: ["fruit-plum"],
      dynamicLinkColor: "rgba(245,158,11,0.9)",
      dynamicLinkWidth: 2.2,
      dynamicLinkOpacity: 1,
      dynamicLinkDash: [10, 2, 3, 2, 1, 4],
      dynamicLinkCap: "round",
      dynamicLinkJoin: "round",
    },
  ];

  return (
    <div style={{ width: "100%", height: 320 }}>
      <DynamicNodes
        nodes={nodes}
        links={links}
        width="100%"
        height="100%"
        background="transparent"
        borderColor="transparent"
        borderRadius={0}
        borderWidth={0}
        defaultLinkColor="rgba(255,255,255,0.25)"
        defaultLinkWidth={1}
        defaultLinkOpacity={1}
        defaultLinkDash={[4, 4]}
        defaultLinkCap="round"
        defaultLinkJoin="round"
        useRandomPositions={false}
        useRandomSpeed={false}
        clampPadding={0}
        animationSpeedMultiplier={1.75}
        fadeMs={700}
        showCanvas={true}
        activateNodes={true}
      />
    </div>
  );
}